default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 400 } %>
  url: <%= ENV.fetch('DATABASE_URL') { "postgresql://coisa:coisa123@localhost:5432/geolocation_#{ENV['RAILS_ENV']}" } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
